### ISSUE TITLE
Implement kafka_connection class

### ISSUE THREAD

**Issue by avelanarius** [psarna/seastar#19]
The class handles a single TCP connection with some specified Kafka broker. 

Later it could store some data about the broker, such as supported API versions.

Initial idea for the class:

```cpp
class kafka_connection {
public:
    seastar::future<> connect(host, port);

    // payload could be char*, std::string or seastar::temporary_buffer<char>
    seastar::future<> write(char *payload);

    seastar::future<seastar::temporary_buffer<char>> read(size_t how_many_bytes);

    seastar::future<> close();
};
```
Test whether it works by connecting to a Kafka broker, sending hardcoded payload and receiving back another payload.

Please test it with Kafka started with https://github.com/avelanarius/seastar/blob/avelanarius-kafkadev-local-final/scripts/kafkadev_local/README.md.

Later versions should expose higher level API such as "send message" (not blob of chars).

`KafkaClient` from Java implementation could be some inspiration: https://github.com/apache/kafka/blob/1a4d44f2067ed8c575d5927fd8361bb99d42b23e/clients/src/main/java/org/apache/kafka/clients/KafkaClient.java
https://github.com/apache/kafka/blob/1a4d44f2067ed8c575d5927fd8361bb99d42b23e/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java

**Comment by avelanarius** [comment]
Example data to send (written in hex, ApiVersions with size and request header): 
```
0000 000E 0012 0002 0000 0000 0004 7465 7374
```

Expected received data (ApiVersions response with size and response header):
```
0000 011C 0000 0000 0000 0000 002d 0000 
0000 0007 0001 0000 000b 0002 0000 0005 
0003 0000 0008 0004 0000 0002 0005 0000 
0001 0006 0000 0005 0007 0000 0002 0008 
0000 0007 0009 0000 0005 000a 0000 0002 
000b 0000 0005 000c 0000 0003 000d 0000 
0002 000e 0000 0003 000f 0000 0003 0010 
0000 0002 0011 0000 0001 0012 0000 0002 
0013 0000 0003 0014 0000 0003 0015 0000 
0001 0016 0000 0001 0017 0000 0003 0018 
0000 0001 0019 0000 0001 001a 0000 0001 
001b 0000 0000 001c 0000 0002 001d 0000 
0001 001e 0000 0001 001f 0000 0001 0020 
0000 0002 0021 0000 0001 0022 0000 0001 
0023 0000 0001 0024 0000 0001 0025 0000 
0001 0026 0000 0001 0027 0000 0001 0028 
0000 0001 0029 0000 0001 002a 0000 0001 
002b 0000 0000 002c 0000 0000 0000 0000 
```

**Comment by StarostaGit** [comment]
https://github.com/psarna/seastar/pull/33
