### ISSUE TITLE
Implement "VARINT" parsing

### ISSUE THREAD

**Issue by avelanarius** [psarna/seastar#21]
VARINT:

Represents an integer between -2^31 and 2^31-1 inclusive. Encoding follows the variable-length zig-zag encoding from Google Protocol Buffers: http://code.google.com/apis/protocolbuffers/docs/encoding.html

**Comment by haaawk** [comment]
You may find this useful:
https://github.com/scylladb/scylla/blob/67a07e9cbc498bbac21a9bb545993232f5a164cb/vint-serialization.hh
https://github.com/scylladb/scylla/blob/67a07e9cbc498bbac21a9bb545993232f5a164cb/vint-serialization.cc
https://github.com/scylladb/scylla/blob/67a07e9cbc498bbac21a9bb545993232f5a164cb/tests/vint_serialization_test.cc
